[wofi]
extra_args = "--allow-markup --columns=1 --hide-scroll"

[menu.shutdown]
title = "Shutdown"
requires_confirmation = "true"

[menu.reboot]
requires_confirmation = "true"

[menu.suspend]
requires_confirmation = "true"

[menu.hibernate]
enabled = "false"
# requires_confirmation = "true"

[menu.logout]
requires_confirmation = "true"

[menu.lock-screen]
title = "Lock Screen"
requires_confirmation = "true"
cmd = "hyprlock"
